export const aliasTable = {
  getRandomNumberBetween: 'randNumber',
  xyCoordinate: 'vec2',
  dynamicRegion: 'vec4',
  mathFloor: 'floor',
  squareRoot: 'sqrt',
  getRandomItemTypeFromItemTypeGroup: 'randItemType',
  stringToNumber: 'str2num',
  getPositionY: 'posY', // prefer to use attribute here, like pos.y, but still retain this function
  undefinedValue: 'undefined',
  getPositionX: 'posX',
  getRandomPositionInRegion: 'randPos',
  substringOf: 'slice',
  absoluteValueOfNumber: 'abs',
  getRandomUnitTypeFromUnitTypeGroup: 'randUnitType',
  getExponent: 'pow',
  numberToString: 'num2str',
  stringToObject: 'str2obj',
  objectToString: 'obj2Str',
  unitsFacingAngle: 'facingAngle',
  getCurrentAmmoOfItem: 'currentAmmo',
  changeDescriptionOfItem: 'changeDesc',
  getItemTypeOfItem: 'itemType',
  getOwnerOfItem: 'owner',
  getUnitTypeOfUnit: 'unitType',
  setFadingTextOfUnit: 'setFadingText',
  getSensorOfUnit: 'sensor',
  getPositionInFrontOfPosition: 'polarProjection',
  getXCoordinateOfRegion: 'regionX',
  getYCoordinateOfRegion: 'regionY',
  playerTypeOfPlayer: 'playerType',
  lastPlayedTimeOfPlayer: 'lastPlayedTime'
}
