export const aliasTable = {
  getRandomNumberBetween: 'randNumber',
  xyCoordinate: 'pos',
  dynamicRegion: 'region',
  mathFloor: 'floor',
  squareRoot: 'sqrt',
  getRandomItemTypeFromItemTypeGroup: 'randItemType',
  stringToNumber: 'str2num',
  getPositionY: 'y', // 'posY' no need to define them specifically
  getPositionX: 'x', // 'posX',
  getXCoordinateOfRegion: 'x', // 'regionX',
  getYCoordinateOfRegion: 'y', // 'regionY',

  getItemTypeOfItem: 'type', // 'itemType',
  getUnitTypeOfUnit: 'type', // 'unitType',
  playerTypeOfPlayer: 'type', // 'playerType',
  getRandomUnitTypeFromUnitTypeGroup: 'type', // 'randUnitType',

  undefinedValue: 'undefined',
  getRandomPositionInRegion: 'randPos',
  substringOf: 'slice',
  absoluteValueOfNumber: 'abs',
  getExponent: 'pow',
  numberToString: 'num2str',
  stringToObject: 'str2obj',
  objectToString: 'obj2Str',
  unitsFacingAngle: 'facingAngle',
  getCurrentAmmoOfItem: 'currentAmmo',
  changeDescriptionOfItem: 'changeDesc',
  getOwnerOfItem: 'owner',
  setFadingTextOfUnit: 'setFadingText',
  getSensorOfUnit: 'sensor',
  getPositionInFrontOfPosition: 'polarProjection',
  lastPlayedTimeOfPlayer: 'lastPlayedTime'
}
