export const aliasTable = {
  getRandomNumberBetween: 'randNumber',
  xyCoordinate: 'pos',
  dynamicRegion: 'region',
  mathFloor: 'floor',
  mathCeiling: 'ceil',
  squareRoot: 'sqrt',
  getRandomItemTypeFromItemTypeGroup: 'randItemType',
  stringToNumber: 'str2num',
  getPositionY: 'y', // 'posY'
  getPositionX: 'x', // 'posX',
  getXCoordinateOfRegion: 'x', // 'regionX',
  getYCoordinateOfRegion: 'y', // 'regionY',
  getOwnerOfItem: 'owner',
  getOwner: 'owner',
  ownerUnitOfSensor: 'owner',
  getItemTypeOfItem: 'type', // 'itemType',
  getUnitTypeOfUnit: 'type', // 'unitType',
  playerTypeOfPlayer: 'type', // 'playerType',
  getRandomUnitTypeFromUnitTypeGroup: 'type', // 'randUnitType',

  undefinedValue: 'undefined',
  getRandomPositionInRegion: 'randPos',
  substringOf: 'slice',
  absoluteValueOfNumber: 'abs',
  getExponent: 'pow',
  numberToString: 'num2str',
  stringToObject: 'str2obj',
  objectToString: 'obj2Str',
  unitsFacingAngle: 'facingAngle',
  getCurrentAmmoOfItem: 'currentAmmo',
  changeDescriptionOfItem: 'changeDesc',
  setFadingTextOfUnit: 'setFadingText',
  getSensorOfUnit: 'sensor',
  getPositionInFrontOfPosition: 'polarProjection',
  lastPlayedTimeOfPlayer: 'lastPlayedTime',

  getLastPurchasedUnit: 'lastPurchasedUnit',
  getLastPlayerSelectingDialogueOption: 'lastSelectingDialogueOption',
  getTriggeringItem: 'triggeringItem',
  playerCustomInput: 'lastPlayerInput',
  getTriggeringRegion: 'triggeringRegion',
  getLastOverlappingUnit: 'lastOverlappingUnit',
  lastPurchasedUnitTypetId: 'lastPurchasedUnitType',
  getTriggeringPlayer: 'triggeringPlayer',
  getLastOverlappedUnit: 'lastOverlappedUnit',
  getLastCreatedItem: 'lastCreatedItem',
  getLastCreatedProjectile: 'lastCreatedProjectile',
  getLastTouchingUnit: 'lastTouchingUnit',
  getLastOverlappingItem: 'lastOverlappingItem',
  entityLastRaycastCollisionPosition: 'lastRaycastCollisionPos',
  getLastCastingUnit: 'lastCastingUnit',
  getLastTouchedUnit: 'lastTouchedUnit',
  getTriggeringProjectile: 'triggeringProj',
  getLastCreatedUnit: 'lastCreatedUnit',
  getTriggeringUnit: 'triggeringUnit',
  getLastTouchedItem: 'lastTouchedItem',
  getLastTouchedProjectile: 'lastTouchedProj',
  getLastOverlappingProjectile: 'lastOverlappingProj',
  getTriggeringAttribute: 'triggeringAttr',
  getLastAttackedUnit: 'lastAttackedUnit',
  getLastAttackingUnit: 'lastAttackingUnit',
  getLastChatMessageSentByPlayer: 'lastChatMessageSent',
  getLastAttackingItem: 'lastAttackingItem',
  entityName: 'name',
  condition: 'if',
  getMax: 'max',
  getMin: 'min'
}
